### ISSUE TITLE
Support pool of neofs nodes

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/rclone#9]
We should be able to specify several neofs-nodes rather than one

**Comment by alexvanin** [comment]
Let's discuss possible pool configuration first. Then implement it.

**Comment by KirillovDenis** [comment]
Current config:
```
[TestNeoFS]
type = neofs
neofs_endpoint = s01.neofs.devenv:8080
wallet = /home/denis/github/nspcc/neofs-dev-env/wallets/wallet.json
address = NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM
basic_acl = public-read-write
placement_policy = REP 1
```

To provide several endpoints in one config param we can use something like `set_env` parameter in `sftp` backend:
```
[TestSFTP]
type = sftp
host = example.com
shell_type = unix
set_env = VAR1=val VAR2=val2
```

So we will be able to use the following config:
```
[TestNeoFS]
type = neofs
neofs_endpoint = s01.neofs.devenv:8080 s02.neofs.devenv:8080 
...
```

To set weights and priority we can define `neofs_priority` and `neofs_weight` param or use
```
s01.neofs.devenv:8080,1,1 s02.neofs.devenv:8080,1,2
```

**Comment by alexvanin** [comment]
Can you confirm these configurations are going to be valid:

```
neofs_endpoint = s01.neofs.devenv:8080

neofs_endpoint = s01.neofs.devenv:8080 s02.neofs.devenv:8080

neofs_endpoint = s01.neofs.devenv:8080,1,1 s02.neofs.devenv:8080,2,1 s03.neofs.devenv:8080,2,9
```

**Comment by KirillovDenis** [comment]
We have to write parser for this. But yes, these configuration are going to be valid.
